### ISSUE TITLE
Add TODOs Badge

### ISSUE THREAD

**Issue by patrickdevivo** [cilium/hubble#110]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/cilium/hubble)](https://www.tickgit.com/browse?repo=github.com/cilium/hubble)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://img.shields.io/endpoint?url=https://api.tickgit.com/badge?repo=github.com/cilium/hubble)](https://www.tickgit.com/browse?repo=github.com/cilium/hubble)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by Rolinh** [comment]
[As for cilium](https://github.com/cilium/cilium/pull/10103#issuecomment-587968694), we'd rather create issues with the label `good-first-issue` for beginners as TODO comments typically lack contextual information.
