### ISSUE TITLE
hubble observe --since does not terminate

### ISSUE THREAD

**Issue by gandro** [cilium/hubble#114]
Using `hubble observe --since T` without any `--until` filter does not terminate automatically anymore, presumably because the server does not close the response and waits for new flows to arrive. This happens until the user terminates the request by presses CTRL+C.

This behavior should only occur if `--follow` is passed. If `--follow` is omitted, the server should close the connection itself if it returned all available flows.

**Comment by glibsm** [comment]
🤔 https://github.com/cilium/hubble/blob/master/cmd/observe/observe.go#L312-L315

**Comment by Rolinh** [comment]
I fail to reproduce it with master, even with a very small ring buffer.

**Comment by gandro** [comment]
I also cannot reproduce on master. I observed this on a work-in-progress Cilium-embedded Hubble branch. I'm closing it for now. Will reopen if I observe it again on a more recent branch.
