### ISSUE TITLE
Feature: publish multi-arch hubble container-image

### ISSUE THREAD

**Issue by mhulscher** [cilium/hubble#1152]
Currently the quay.io/cilium/hubble image contains an amd64 build. I'd love to have a multi-arch image with at least arm64 included.

**Comment by glibsm** [comment]
In the hubble Makefiles we build for multiple platforms https://github.com/cilium/hubble/blob/main/Makefile#L43-L53 and when the releases are cut those are attached https://github.com/cilium/hubble/releases/tag/v0.12.0

It makes sense to fix the images also, not sure what's going on there
