### ISSUE TITLE
 Enhancement: report file/line information for drop notifications

### ISSUE THREAD

**Issue by julianwiedmann** [cilium/hubble#1216]
https://github.com/cilium/cilium/pull/20387 introduced source file/line information for drop notifications. The PR also added `cilium monitor` support.

It would be great to also surface this error information in hubble.

**Comment by sadath-12** [comment]
assign me please

**Comment by Gnoale** [comment]
Hello, can you point me in the right direction / elaborate about this one ? I'd like to contribute

**Comment by Gnoale** [comment]
Something seems off in the vendor folder : it is missing a lot of files from `pkg/monitor/`  although the tag that is vendor into this repository has all these files, among them  `datapath_drop.go` which hold the `DropNotify` struct 
```
✔ ~/git/cilium [v1.15.3|✔] 
11:47 $ ls pkg/monitor/
agent              datapath_debug_test.go  datapath_policy_test.go      datapath_trace.go       format         types.go
alignchecker       datapath_drop.go        datapath_recorder.go         datapath_trace_test.go  logrecord.go
api                datapath_drop_test.go   datapath_sock_trace.go       dissect.go              notifications
datapath_debug.go  datapath_policy.go      datapath_sock_trace_test.go  dissect_test.go         payload
```

My guess is hubble should somehow build this object and so get access to the `DumpInfo` function to print all the information mentioned

**Comment by glibsm** [comment]
@sadath-12 are you still interested in working on this issue?

**Comment by Gnoale** [comment]
Up ?

**Comment by julianwiedmann** [comment]
Resolved with https://github.com/cilium/cilium/pull/34616.
