### ISSUE TITLE
observe does not print anything when the ring buffer is full

### ISSUE THREAD

**Issue by Rolinh** [cilium/hubble#131]
When the ring buffer is full, queries such as `hubble observe --since 1h` or `hubble observe --last 1000` (with a ring buffer of size < 1000) does not print out anything.

/cc @gandro who observed this behavior while trying to reproduce #114

**Comment by Rolinh** [comment]
@michi-covalent I believe this is what happens:
First, [`newRingReader()`](https://github.com/cilium/cilium/blob/c6fa3f9f8b4b658f693f1ecd49539095dd584324/pkg/hubble/observer/local_observer.go#L428)  positions the offset to match the request parameters. Then, the [`flowsReader()`](https://github.com/cilium/cilium/blob/c6fa3f9f8b4b658f693f1ecd49539095dd584324/pkg/hubble/observer/local_observer.go#L357) uses the ring reader to read through the ring buffer. However, in the meantime, the entry at which the ring reader points to has been overwritten by a more recent event.
This means that [`flowsReader.Next()`](https://github.com/cilium/cilium/blob/c6fa3f9f8b4b658f693f1ecd49539095dd584324/pkg/hubble/observer/local_observer.go#L387) stops prematurely because the event no longer matches the request parameter, typically because it's [too new](https://github.com/cilium/cilium/blob/c6fa3f9f8b4b658f693f1ecd49539095dd584324/pkg/hubble/observer/local_observer.go#L411). 
A solution could be to keep reading in such a case assuming that an oldest event might come next.

**Comment by gandro** [comment]
I think I see similar issues (albeit with `follow`) when trying to write CI tests.

@Rolinh I agree that the check for events which are "too new" might too eager. However, the issue also seems to occur with `--last N`, where we don't have time ranges.

**Comment by gandro** [comment]
Another (potentially related) observation: `hubble observe --last 10000` works for a non-full ring-buffer, even if there are less than 10000 flows available. `hubble observe --follow --last 10000` on the same ring buffer however does not return anything.

**Comment by gandro** [comment]
Another observation: There is also a fundamental problem that requests which are supposed to dump all flows (e.g. `hubble observe --since 10000h`) are very likely to fail due to a concurrent write invalidating the oldest entry and therefore requiring the reader to abort the request.

**Comment by Rolinh** [comment]
I think that for requests that dump all flows, we should look at #253 as it makes more sense overall (I'm not dismissing the issue though).

**Comment by michi-covalent** [comment]
related to #253, if the fix for this is not trivial, i'd suggest adding an optional flag to the GetFlowsRequest:
```
// Returns flows in descending order by time. Incompatible with the follow option.
bool descending = 9;
```
this will not change the current behavior, but if this flag is set, we can traverse the ring buffer without rewinding.

**Comment by glibsm** [comment]
To add another repro case, there are four L7 flows in the buffer, going to `--last` over 4 results in no flows (rewind too far stops?)

```
bash-5.0# hubble observe --pod tiefighter -t l7 --last 1
TIMESTAMP             SOURCE                   DESTINATION                TYPE            VERDICT     SUMMARY
May  4 19:22:23.106   104.198.14.52:80(http)   default/tiefighter:59196   http-response   FORWARDED   HTTP/1.1 301 61ms (GET http://cilium.io/)
bash-5.0# hubble observe --pod tiefighter -t l7 --last 2
TIMESTAMP             SOURCE                     DESTINATION                TYPE            VERDICT     SUMMARY
May  4 19:22:23.045   default/tiefighter:59196   104.198.14.52:80(http)     http-request    FORWARDED   HTTP/1.1 GET http://cilium.io/
May  4 19:22:23.106   104.198.14.52:80(http)     default/tiefighter:59196   http-response   FORWARDED   HTTP/1.1 301 61ms (GET http://cilium.io/)
bash-5.0# hubble observe --pod tiefighter -t l7 --last 10
```
