### ISSUE TITLE
observe --follow terminates when buffer is empty

### ISSUE THREAD

**Issue by michi-covalent** [cilium/hubble#134]
this might be related to #131, but i'm seeing a slightly different issue where `observe --follow` terminates when ring buffer is *empty*. i looked into it a bit, basically what happens is:

- flow is nil here: https://github.com/cilium/hubble/blob/00dc35a7f50dedea536c2b987b9fce1f8a079556/pkg/container/ring.go#L180
- NextFollow returns nil event: https://github.com/cilium/hubble/blob/00dc35a7f50dedea536c2b987b9fce1f8a079556/pkg/container/ring_reader.go#L75
- local observer returns io.EOF: https://github.com/cilium/hubble/blob/00dc35a7f50dedea536c2b987b9fce1f8a079556/pkg/server/local_observer.go#L311
- getFlows terminates: https://github.com/cilium/hubble/blob/00dc35a7f50dedea536c2b987b9fce1f8a079556/pkg/server/local_observer.go#L201

**Comment by Rolinh** [comment]
Thanks for the report, I'll have a look.
