### ISSUE TITLE
About 0.13.1 release

### ISSUE THREAD

**Issue by chenrui333** [cilium/hubble#1410]
👋 looks like 0.13.1 release did not get completed, ie the release did not get marked as latest release, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/165565

**Comment by rolinh** [comment]
Hi, it seems indeed that the release process is not yet complete (cc @chancez). Thanks for letting us know! The release process should be completed today.

**Comment by chancez** [comment]
Yeah we were waiting on approvals, release is still in process. Also; the image build failed so we're likely going to just proceed with 0.13.2 instead.
