### ISSUE TITLE
Replace request lib with something different in hubble-ui

### ISSUE THREAD

**Issue by geakstr** [cilium/hubble#145]
Pull request with patch https://github.com/cilium/hubble-ui/pull/8
Issue with request dep https://github.com/request/request/issues/3274

**Comment by Rolinh** [comment]
@geakstr It looks like this library is not maintained anymore. From [the readme](https://github.com/request/request/blob/master/README.md):
> As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. In fact, none have landed for some time.

See also [this issue](https://github.com/request/request/issues/3142). It looks like it's time to consider an alternative.

**Comment by geakstr** [comment]
@Rolinh thanks, I've updated the title

**Comment by bengentil** [comment]
@geakstr Replacing request in hubble-ui in not sufficient, request is used almost everywhere in the kubernetes-client, so this depends also on https://github.com/kubernetes-client/javascript/issues/414
