### ISSUE TITLE
Revisit integer sizes in protobuf definitions

### ISSUE THREAD

**Issue by gandro** [cilium/hubble#158]
Some of our integer sizes in the protobuf definitions are too large. If we can afford a breaking change, we should resize them to appropriate sizes.

Example:
https://github.com/cilium/hubble/blob/23ae0b9c2a2d399789faf6189db8820063b608c0/api/v1/flow/flow.proto#L114
Cilium numeric security identities are 32 bit. We should use a uint32 here.

Unfortunately protobuf does not have a `uint16` type, which would be appropriate for things like port numbers or `pb.Endpoint.ID`. We will have to keep using `uint32` there.

**Comment by matej-g** [comment]
I see this code has been moved over after #220, is this still a valid issue? If so, I'd like to take it (perhaps over at Cilium repo)

**Comment by gandro** [comment]
It's still a valid issue, and yes it would have to be done on the Cilium repository.

I would like to mention however that we do not want to do any breaking changes to the gRPC API right now. However, if I read https://developers.google.com/protocol-buffers/docs/encoding correctly, then changing an integer size does not break the wire-format. Therefore, fixing the integer sizes should be okay!

**Comment by matej-g** [comment]
Thanks for the confirmation, and sorry for the delay!

Indeed, this change should not be breaking - https://developers.google.com/protocol-buffers/docs/proto3#updating

Opened a PR https://github.com/cilium/cilium/pull/11161 - would appreciate feedback!
