### ISSUE TITLE
`GetEventsChannel` buffer size too small embedded Hubble

### ISSUE THREAD

**Issue by gandro** [cilium/hubble#161]
The current default is too small for embedded Hubble. From https://github.com/cilium/cilium/pull/10238/files#r385174692:

> The issue seems to be that `GetEventsChannel()` buffer size is too small for the "Embedded Mode": By default, the channel returned `GetEventsChannel` will only store 81 flows (1% of the next power of two of `--max-flows`). This queue size is way to small to deal with short bursts.
> 
> The previous buffer size (in Hubble stand-alone mode) has been `GetEventsChannel()` (up to 100 flows) + Cilium monitor's socket queue, which is `1024*NumberOfCPUs` (capped at `16384`).

**Comment by gandro** [comment]
Note: While the Hubble side has been merged, the Cilium change still has to be done.

**Comment by michi-covalent** [comment]
i'll take care of it

**Comment by gandro** [comment]
Closed via https://github.com/cilium/cilium/pull/10488
