### ISSUE TITLE
flow: Add filters for source and destination endpoint identities

### ISSUE THREAD

**Issue by michi-covalent** [cilium/hubble#191]
this makes it easier for hubble ui to group flows by security identity. we can also add a filter to filter by security identity so that you don't need to specify all the labels.

**Comment by michi-covalent** [comment]
maybe just Identity.ID is enough to start with.

**Comment by michi-covalent** [comment]
... i don't know how i missed that we already have the id field:
```
  "source": {
    "ID": "3726",
    "identity": "9578",
    "namespace": "kube-system",
    "labels": [
      "k8s:io.cilium.k8s.policy.cluster=default",
      "k8s:io.cilium.k8s.policy.serviceaccount=coredns",
      "k8s:io.kubernetes.pod.namespace=kube-system",
      "k8s:k8s-app=kube-dns"
    ],
    "pod_name": "coredns-86c58d9df4-fswfg"
  },
  "destination": {
    "identity": "1",
    "labels": [
      "reserved:host"
    ]
  },
```
i guess the id field is not set for reserved entities. will look into it a bit.

**Comment by michi-covalent** [comment]
ok so "1" for reserved:host is supposed to be an ID and not identity. from cilium's endpoint API:
```
  {
    "id": 1,
    "labels": [
      "reserved:host"
    ],
    "labelsSHA256": "e4faf1094f0345379a564e072a74e9c130c4c628b585b75f6be16dbcfd8d1b49"
  }
```
i'll fix it so that we can consistently use the ID field.

**Comment by michi-covalent** [comment]
... well i guess `"id"` in the cilium endpoint corresponds to the "identity" field in hubble flow. i'll add filters for source and destination identities.

**Comment by gandro** [comment]
Having filters on the endpoint id would also be useful to match parity with `cilium monitor` (which has `--related-to` filters for the endpoint id as well).
