### ISSUE TITLE
Support custom connection metrics from Prometheus

### ISSUE THREAD

**Issue by ivanayov** [cilium/hubble#204]
Hello,

I had a look at the project tutorials/documentation/code and it looks like a good solution for our use-case, but I'm not sure if it's compatible with our API/tools. Any feedback and guidance from the community are highly welcome.

[NetworkServicemesh](http://networkservicemesh.io) is a project that creates L2/L3 connectivity between pods, based on gRPC. For each pod-to-pod connection, we expose to Prometheus metrics like transmissed/received bytes, packets, and error packets between the specified pods.

I deployed NSM together with Hubble and a 4G-network NSM example but it seems that the connections are not discovered. 

<img width="745" alt="Screenshot 2020-03-25 at 19 44 38" src="https://user-images.githubusercontent.com/4160133/77568563-7813b880-6ed1-11ea-9206-31cc8e545270.png">

What we would like to achieve is to have all connections displayed and for each connection to have TX/RX bytes/packets data from Prometheus exposed in the UI.

Can you please share some guidance or starting point?
Thanks

**Comment by gandro** [comment]
Hi @ivanayov! A common problem with connections not being discovered is that the pods themselves are not managed by Cilium yet, therefore we don't get any flow information.

If you installed Hubble/Cilium after NSM, you will need to restart the NSM pods. We have a script for that. See https://docs.cilium.io/en/v1.7/troubleshooting/#ensure-pod-is-managed-by-cilium for details.

**Comment by glibsm** [comment]
Closing as stale due to age. Please feel free to reopen the ticket if still relevant.
