### ISSUE TITLE
Helm Chart: Incorrect versions in values.yaml

### ISSUE THREAD

**Issue by seanmwinn** [cilium/hubble#227]
```
git checkout v0.5.0
cd install/kubernetes/hubble
helm install hubble . 
```

expected results: v0.5.0 tagged container deployed
actual results: latest tagged container deployed

```
git checkout master
cd install/kubernetes/hubble
helm install hubble .
```

expected results: latest tagged container deployed
actual results: v0.5.0 tagged container deployed

**Comment by glibsm** [comment]
Fixing 0.5 to have 0.5 is a chicken and egg issue, but can be resolved by changing the template to have 0.5 tag right before it's released.

For master we can change back to `:latest`
