### ISSUE TITLE
[Feature] Persistent Storage Option for Flows

### ISSUE THREAD

**Issue by daviddyball** [cilium/hubble#23]
Are there any plans to implement persistent storage for flow data? Understandably this would require a lot of storage space, but it might be a useful feature to consider.

**Comment by nicolastakashi** [comment]
Hi, @tgraf could this be achieved through Prometheus integration?

**Comment by rolinh** [comment]
Hi, there is no plan currently to add persistent storage support for Hubble flows. If you need such a feature today, you have 2 options:

- Setup Hubble to export flows to a rotated file (see `hubble-export-file-path` flag of the Cilium agent) then use a mechanism to send these flows to a system where they can be collected and analyzed (e.g. Elasticsearch).
- Use [Isovalent's Hubble Timescape](https://isovalent.com/cilium-timescape/) which implements such a feature (see also [Introduction to Hubble Timescape](https://www.youtube.com/watch?v=xBgzuuHOFsI)).
