### ISSUE TITLE
Helm: Setting cri.runtime to any runtime results in --cri-endpoint unknown flag error

### ISSUE THREAD

**Issue by seanmwinn** [cilium/hubble#230]
```
helm upgrade hubble . --namespace kube-system --set image.tag="v0.5.0" \
--set metrics.enabled="{dns:query;ignoreAAAA;destinationContext=pod-short,drop:sourceContext=pod;destinationContext=pod,tcp,flow,port-distribution,icmp,http}" \
--set ui.enabled=true --set cri.runtime="docker"
Release "hubble" has been upgraded. Happy Helming!
NAME: hubble
LAST DEPLOYED: Mon Apr 13 13:42:37 2020
NAMESPACE: kube-system
STATUS: deployed
REVISION: 9
TEST SUITE: None
sean.winn@Seans-MacBook-Pro hubble % kubectl logs -n kube-system hubble-fw79m
time="2020-04-13T20:42:28Z" level=fatal msg="main program execution encountered a fatal error" error="unknown flag: --cri-endpoint"
```

Tested with docker, contained, crio and any/all values result in the same error message. 

Was support for customizing the cri socket path removed?

**Comment by gandro** [comment]
> Was support for customizing the cri socket path removed?
Yes. We can remove the option from the helm chart in the 0.5 branch I guess.

For `master`, it doesn't make sense to keep the server-side Helm charts around for much longer anyways, since almost everything got moved to the cilium/cilium repository (the Helm chart move is the only thing still WIP).

**Comment by Rolinh** [comment]
No longer relevant as charts moved to the cilium repository.
