### ISSUE TITLE
network: unable to connect to Cilium daemon

### ISSUE THREAD

**Issue by llussy** [cilium/hubble#238]
**I would like to ask how to clean up the cilium environment**

**[I follow the official documentation](https://github.com/cilium/hubble/blob/master/Documentation/installation.md)** 

```bash
# install
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.7.0/install/kubernetes/quick-install.yaml
```

```bash
# delete
kubectl delete -f https://raw.githubusercontent.com/cilium/cilium/v1.7.0/install/kubernetes/quick-install.yaml
```

After that, I found that all my pods cannot be created properly.
about cilium crd,I have deleted. Do i need to delete anything？

## Error message
```bash
# kubectl get pod  | grep httpd
httpd-596db6fdc4-4r22k                                 0/1     ContainerCreating   0          15m
httpd-596db6fdc4-5xldk                                 0/1     ContainerCreating   0          15m

# kubectl describe pod
Events:
  Type     Reason                  Age    From                             Message
  ----     ------                  ----   ----                             -------
  Normal   Scheduled               10m    default-scheduler                Successfully assigned default/httpd-596db6fdc4-5xldk to node001
  Warning  FailedCreatePodSandBox  9m17s  kubelet, node001  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ffcd455f1ab5483a17f87cdad35beaea980e61317dbe35b788cac7953e72c95f" network for pod "httpd-596db6fdc4-5xldk": NetworkPlugin cni failed to set up pod "httpd-596db6fdc4-5xldk_default" network: unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

**Comment by llussy** [comment]
How do I get him not to use it **Cilium** ？ Thank you.

**Comment by Rolinh** [comment]
> How do I get him not to use it Cilium

Are you trying to run Hubble without Cilium? This is not possible, Cilium is a requirement for Hubble.

**Comment by llussy** [comment]
> > How do I get him not to use it Cilium
> 
> Are you trying to run Hubble without Cilium? This is not possible, Cilium is a requirement for Hubble.

![image](https://user-images.githubusercontent.com/18432966/79847860-e70dff80-83f2-11ea-91fd-c1825cba0df1.png)
I followed the documentation only for the first step，Now my entire environment is abnormal and cannot create pods properly.

I want to ask for a way to empty Cilium environment？ I delete this yaml and crd. my environment is still abnormal.

**Comment by gandro** [comment]
It's hard to say what exactly is broken without more details. The quick install is intended for sandbox environment. If you have sophisticated setup, you will need to follow the linked `Install instructions` guide.

To perform a proper cleanup and removal of Cilium, you can try to re-deploy the Cilium 1.7 chart via Helm with the following arguments. It will perform a cleanup of the nodes without actually running Cilium agent:

```
helm repo add cilium https://helm.cilium.io/
helm install cilium cilium/cilium --version 1.7.2 \
  --namespace kube-system \
  --set agent.sleepAfterInit=true --set global.cleanState=true --set global.cleanBpfState=true
```

If that fixes your issue, you can use `helm delete` to uninstall the DaemonSet and remove the CRDs again.

**Comment by llussy** [comment]
> It's hard to say what exactly is broken without more details. The quick install is intended for sandbox environment. If you have sophisticated setup, you will need to follow the linked `Install instructions` guide.
> 
> To perform a proper cleanup and removal of Cilium, you can try to re-deploy the Cilium 1.7 chart via Helm with the following arguments. It will perform a cleanup of the nodes without actually running Cilium agent:
> 
> ```
> helm repo add cilium https://helm.cilium.io/
> helm install cilium cilium/cilium --version 1.7.2 \
>   --namespace kube-system \
>   --set agent.sleepAfterInit=true --set global.cleanState=true --set global.cleanBpfState=true
> ```
> 
> If that fixes your issue, you can use `helm delete` to uninstall the DaemonSet and remove the CRDs again.

**My helm is also abnormal** テ_デ
```bash
# helm install cilium cilium/cilium --version 1.7.2 \
>   --namespace kube-system \
>   --set agent.sleepAfterInit=true --set global.cleanState=true --set global.cleanBpfState=true
Error: could not find a ready tiller pod


Events:
  Type     Reason                  Age                   From                             Message
  ----     ------                  ----                  ----                             -------
  Normal   SandboxChanged          54m (x33 over 105m)   kubelet, node0001  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  4m28s (x55 over 89m)  kubelet, node0001  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b4c2f56c24e700db6ad1a8a64fe09189f585a3a6b8aa5c6131fbe7b87317f5b6" network for pod "tiller-deploy-68f9c68579-t8tt5": NetworkPlugin cni failed to set up pod "tiller-deploy-68f9c68579-t8tt5_kube-system" network: unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

**Comment by gandro** [comment]
This is expected with Helm 2. However, we highly recommend you use Helm 3, as it does not require tiller.

**Comment by llussy** [comment]
> This is expected with Helm 2. However, we highly recommend you use Helm 3, as it does not require tiller.
> 
> Edit: If you really need to use to use a Helm 2 client binary, please use `helm template` instead of `helm install` to generate the Cilium YAML manifest.

My environment is not working anymore, there should be something related to cilium  not deleted.
I now want to delete everything about cilium, first restore my environment.

**Comment by gandro** [comment]
If you run the above `helm install` command with Helm 3, then Cilium will try to restore the environment or you. Once that succeeds, you can remove Cilium again. Just deleting the Cilium DaemonSet is not enough to uninstall it!

**Comment by llussy** [comment]
> If you run the above `helm install` command with Helm 3, then Cilium will try to restore the environment or you. Once that succeeds, you can remove Cilium again. Just deleting the Cilium DaemonSet is not enough to uninstall it!

Now normal，I found `/etc/cni/net.d/05-cilium.conf` and I deleted it on all nodes，`systemctl restart kubelet`,The cluster is back to normal. thank you.
