### ISSUE TITLE
Update deploy-hubble-servicemap/README.md

### ISSUE THREAD

**Issue by michi-covalent** [cilium/hubble#244]
start using cilium embedded hubble

---

the readme current points to cilium config file where embedded hubble is off

**Comment by michi-covalent** [comment]
link to the readme file https://github.com/cilium/hubble/blob/master/tutorials/deploy-hubble-servicemap/README.md

**Comment by glibsm** [comment]
https://raw.githubusercontent.com/cilium/cilium/master/install/kubernetes/quick-install.yaml points to config with hubble off though, no?

**Comment by michi-covalent** [comment]
yes, hubble needs to be turned on with the helm option. also needs to open up a tcp port with `hubble-listen-addresses` so that the UI can connect to hubble.

**Comment by Rolinh** [comment]
I think this has been fix in #305. Feel free to reopen if not.
