### ISSUE TITLE
Rate-limits / Circuit-breakers to limit Cilium API calls made by Hubble

### ISSUE THREAD

**Issue by danwent** [cilium/hubble#265]
This issue is specific to Hubble with Cilium 1.7 and earlier, and is not relevant for embedded Hubble in Cilium 1.8 . 

Hubble fetches metadata (e.g., identity labels) for src + dst of each flow via the cilium APIs. This means the number of API calls it make to cilium can depend on the set of flows that appear on a node, and the identities associated with those flows.   Hubble caches this flow data, but scenarios like a large number of new or unknown identities can result in a potentially large number of Cilium API requests.    

A particularly bad scenario is where a flow may contain an IP for which cilium has no identity, which means hubble will not cache an identity, and that each flow with that IP may result in another API call.  

This issue is to explore whether there are simple improvements to the non-embedded version of hubble that can: 
(1) cap the overall number of requests that hubble makes to Cilium within a time window (or perhaps the max outstanding requests).  
(2) limit the impact of certain pathological cases, such as repeated lookups for an IP with no associated identity.  

Note, changes of both types may be ideal, as (1) will likely mean that we have to "fail hard" and not associate identity with flows when some cap is reached.  Thus, having something like (2) which can reduce the volume of potentially "high rate, low value" queries will help "protect" more valid lookups.

**Comment by glibsm** [comment]
Seems like case (2) is the leading cause of (1) and addressing this through a global limit of requests will actually have other unintentional consequences, like preventing real ips from being resolved in live flows because a bad IP has used up the entire quota.

I think starting with (2) and implementing back-off on failed lookups of the same IP is probably a good first step and then we can get some more data

**Comment by tgraf** [comment]
> I think starting with (2) and implementing back-off on failed lookups of the same IP is probably a good first step and then we can get some more data

Yes, I was about to propose this as well. If we limit per IP with a burst setting, then the side effects are a lot less. It will make it a lot harder to find a good default setting though.

**Comment by glibsm** [comment]
We'll get this into 0.5.2
