### ISSUE TITLE
hubble status reports flows as NaN when used against hubble relay

### ISSUE THREAD

**Issue by errordeveloper** [cilium/hubble#303]
I have seen it once, not been able to reproduce, but opening the issue on @Rolinh's request.

**Comment by Rolinh** [comment]
This can happen only if `MaxFlows` value (see [here](https://github.com/cilium/hubble/blob/f23413f886e2fb04194eb6f769decffea3cab9c4/cmd/status/status.go#L71)) is somehow `0`. Not sure how could this be but it has to be investigated on the Hubble server side.

**Comment by gandro** [comment]
> This can happen only if `MaxFlows` value (see [here](https://github.com/cilium/hubble/blob/f23413f886e2fb04194eb6f769decffea3cab9c4/cmd/status/status.go#L71)) is somehow `0`. Not sure how could this be but it has to be investigated on the Hubble server side.

@Rolinh  I have seen it as well. It can be reproduced if hubble-relay is not connected to any nodes (e.g. due to broken node connectivity). We can fix the NaN in the CLI for sure, but I'm also wondering if we should add the `NodeStatusEvent` to `hubble status` to inform clients about unavailable nodes.

**Comment by Rolinh** [comment]
> I'm also wondering if we should add the NodeStatusEvent to hubble status to inform clients about unavailable nodes.

I think this would be a great addition! Especially since `status` should report the... well... status :)

**Comment by Rolinh** [comment]
> > I'm also wondering if we should add the NodeStatusEvent to hubble status to inform clients about unavailable nodes.
> 
> I think this would be a great addition! Especially since `status` should report the... well... status :)

@gandro This is implemented in #328 and in https://github.com/cilium/cilium/pull/12655 server side.
