### ISSUE TITLE
Hubble UI shows an error "Failed to get flows: Error: Need namespace specified" when clicking on the gear icon for "Host"

### ISSUE THREAD

**Issue by joestringer** [cilium/hubble#331]
![image](https://user-images.githubusercontent.com/1243336/88743515-c217df80-d0f9-11ea-96a8-ea32305ee645.png)

* `docker.io/cilium/cilium:latest`
* `docker.io/cilium/hubble-relay:latest`
* `quay.io/cilium/hubble-ui:v0.6.1`

This is probably because the host doesn't have a kubernetes namespace.

**Comment by joestringer** [comment]
The same behaviour also affects `remote-node` or `world` or an FQDN name.

To reproduce, deploy Cilium + Hubble + Cilium "connectivity-check.yaml`.

**Comment by gandro** [comment]
I have observed this as well for FQDN endpoints - @yandzee @geakstr
