### ISSUE TITLE
Using Hubble with a different CNI (different networking solution)

### ISSUE THREAD

**Issue by GalSagie** [cilium/hubble#44]
Have a different CNI for Kubernetes (Other then Cilium) but still have the ability to leverage Hubble for visibility

**Comment by gandro** [comment]
Please note that Cilium supports CNI chaining, i.e. you can use Cilium on top of another CNI. This will allow you to use another networking solution, while Hubble can still rely on Cilium for gathering flow data: https://docs.cilium.io/en/v1.6/gettingstarted/cni-chaining/
