### ISSUE TITLE
CLI support for TCP flags filter

### ISSUE THREAD

**Issue by gandro** [cilium/hubble#453]
Support for TCP flag filtering on the server-side has landed in https://github.com/cilium/cilium/pull/13826. This issue tracks the client side flags needed to send requests with such filters set.

**Comment by Rolinh** [comment]
Regarding how this would be implemented, there was an initial proposal on  https://github.com/cilium/cilium/issues/12827#issuecomment-676512342. On one hand, I like it. On the other hand, it think it might be easy for a user to miss this functionality. It also wouldn't be consistent with e.g. the way we do it for http filters. What about adding a new `--tcp-flags` (that would imply `--protocol tcp`)? I think this could work especially well with auto-completion of TCP flags (similar to what is done for `http-method` for instance).

**Comment by nyrahul** [comment]
I would like to take up this issue. Can you assign it to me?
