### ISSUE TITLE
Document pod/service filter prefix behavior

### ISSUE THREAD

**Issue by rolinh** [cilium/hubble#501]
This is the current help message for the pod and service filters:
```
      --from-pod filter         Show all flows originating in the given pod name ([namespace/]<pod-name>). If namespace is not provided, 'default' is used
      --from-service filter     Show all flows originating in the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
      --pod filter              Show all flows related to the given pod name ([namespace/]<pod-name>). If namespace is not provided, 'default' is used
      --service filter          Show all flows related to the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
      --to-pod filter           Show all flows terminating in the given pod name ([namespace/]<pod-name>). If namespace is not provided, 'default' is used
      --to-service filter       Show all flows terminating in the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
```

It appears that `<pod-name>` and `<service-name>` are treated as prefixes for the actual pod or service name. This allows performing queries like `hubble observe --pod cilium` to get all flows related to pods which name starts with `cilium`. This behavior is currently undocumented.

**Comment by rolinh** [comment]
Hey @slayer321,

What is undocumented is that the these filters are not _exact_ match, they are _prefix_ match. In other words, `hubble observe --pod kube-system/cilium` will match _every_ cilium pod as their names start with `cilium` although the full name is something like `cilium-phzv7`. Is this explanation more clear?

**Comment by slayer321** [comment]
Yeah, Now I'm able to understand it. Will raise a PR now :)
