### ISSUE TITLE
Upload helm chart to repository

### ISSUE THREAD

**Issue by dsexton** [cilium/hubble#52]
It would be great if the hubble chart was also packaged and uploaded to the chart repository.

See:

- https://github.com/cilium/cilium/pull/9772
- https://github.com/cilium/cilium/blob/master/contrib/release/uploadrev

**Comment by alex1989hu** [comment]
👍

**Comment by masterkain** [comment]
I'm also kinda confused by the installation method.

https://github.com/cilium/hubble/blob/master/Documentation/installation.md

doesn't mention helm

https://github.com/cilium/hubble/blob/master/Documentation/metrics.md

and this page above does. so I have a hubble installation but how to install metrics in this case?
are there helm installation instructions?

**Comment by michi-covalent** [comment]
hi @masterkain 

the default minikube yaml file is generated using helm with some default metrics:

https://github.com/cilium/hubble/blob/a6feb58d66c9aaa8874b925cffcdf20564edd034/tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml#L180

so if you follow https://github.com/cilium/hubble/blob/master/Documentation/installation.md you already have metrics enabled. you can exec into the hubble pod and run something like `curl localhost:6943/metrics` to see all the prometheus metrics.

https://github.com/cilium/hubble/blob/master/Documentation/metrics.md is a more detailed documentation for all the available metrics in case you need to customize which metrics to enable.

**Comment by Hades32** [comment]
I just wasted quite some time, wondering why Cilium worked and Hubble did not, when using https://helm.cilium.io/

**Comment by gandro** [comment]
> I just wasted quite some time, wondering why Cilium worked and Hubble did not, when using https://helm.cilium.io/

With the Cilium 1.8 release coming up, we will provide the Helm charts for all Hubble components for Hubble 0.6 under https://hem.cilium.io as well.
