### ISSUE TITLE
OpenTelemetry Support

### ISSUE THREAD

**Issue by trnl** [cilium/hubble#531]
Dear Hubble Community, 

We are currently migrating to Cilium as our networking solution and are very excited to use Hubble for observability. 

However, we miss one thing to be happy – OpenTelemetry (OpenTracing) support. I can see it was mentioned in the roadmap around Cilium 1.0 [release](https://cilium.io/blog/2018/04/24/cilium-10):
> h3. The Roadmap Ahead
> Integration with OpenTracing, Jaeger, and Zipkin: The minimal overhead of BPF makes it the ideal technology to provide tracing and telemetry functionality without imposing additional system load.

However, I haven't found any code/issues connected to it. I thought that might be [Cilium Go Extensions](https://docs.cilium.io/en/v1.6/envoy/extensions/) is the right place to implement it. Then I checked Hubble, and it looks like all the data required is in place. I can potentially contribute to it if you give some guidance if Hubble Relay the right place for it.

**Comment by rolinh** [comment]
Hi @trnl and thanks for opening this issue :wave: 

Would you mind detailing your use-case so that we can have a better understanding of the value proposition of such a feature?

It is also not yet clear to me what this would mean in terms of integration. Could you expand a bit on this as well please?

**Comment by trnl** [comment]
@rolinh is simple - observability enhancement. 

Currently, in Hubble, you have two aspects: metrics and flows. While Prometheus can consume metrics from Hubble, flows are not exported in an open standard. They are accessible just via hubble-cli and service graph in hubble-ui. They also can't be used for distributed transaction timing and analysis. 

However, as I see, flows have everything to become the source for traces in OpenTracing (OpenTelemetry) format. You can send the data to any OpenTelemetry collector (Jaeger, Zipkin, ElasticAPM, or Grafana Tempo) and have complete visibility into the transactions. 

Most of our communication is simple HTTP + PostgreSQL requests. If implemented, this will move tracing responsibility from the application (Java/NGINX containers) to infrastructure (Cillium) and eliminate the need for independent configuration of components (ex. [ingress-controller](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md#enable-opentracing)). It will also make Cillium closer to service mesh solutions.

With Layer7 visibility enabled, Cilium can produce traces not only for HTTP, but potentially to other protocols as well. If Layer 7 visibility is not enabled - even L4 traces can be interesting.

**Comment by trnl** [comment]
Upon writing the previous comment I realised that you still need to propane the SpanContext (Trasaction Information) somehow. 
Istio requires you to propagate these headers in application code: https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation

Besides that, with non-HTTP protocols there should be a place in the message container where clients can set the markers. For example in PostgreSQL wire protocol there is no place for custom metadata as far as I can see.

Ok, I see now why you have only flows and service map (who communicates with whom), but no transactions.

**Comment by shayn1234** [comment]
@trnl can you explain your last comment "Ok, I see now why you have only flows and service map (who communicates with whom), but no transactions." why can't we propagate it using HTTP headers in Cillium?

**Comment by trnl** [comment]
@shayn1234, let's assume transaction: Service **A** communicates with Service **B** and Service **B** with Service **C**
```
A -> B -> C
```

Cilium observing all the communication between them. So it can see that **A** send HTTP request to **B** and few moments later **B** send request to **C**. But crucial question here - how Cilium can link 1st request with the 2nd to say - it's transaction? Some marker, aka context should be in place. But the thing is that it depends on internal implementation on **B**. For example incoming (A->B) and outgoing (B->C) HTTP requests can be done by completely independent classes, threads, libraries. You also need to take into account that **B** potentially processing requests from D, E, F and automatic linking is impossible. At the end you need a custom logic in **B** to ensure that context picked from incoming request and pushed to outgoing. 

This is something Cilium folks can't influence. Even if they'll put context in A->B it will be likely lost on B->C.

**Comment by glibsm** [comment]
> This is something Cilium folks can't influence. Even if they'll put context in A->B it will be likely lost on B->C.

That is correct. It is not possible to do this kind of distributed tracing without user libraries (such as HTTP middleware) that automatically either creates a new, or extends an existing trace. Even though Cilium sees all the traffic, it is not possible to correlate without that information.

**Comment by shayn1234** [comment]
Sure I understand. You can take even a simpler example that B gets multiple requests from A and sends multiple requests to C. You cannot tel which is which and you loose it. 

Thanks @glibsm

**Comment by trnl** [comment]
@rolinh, 

There is may be one question - if headers are already in place in the traffic (X-B3-TraceId for example for Zipkin) or others, is it possible somehow to extract them via Cilium and submit traces to Zipkin/Otel-Collector? 

-vova

**Comment by gandro** [comment]
See also https://github.com/cilium/hubble-otel
