### ISSUE TITLE
GetNodes not implemented

### ISSUE THREAD

**Issue by christian-2** [cilium/hubble#567]
Is this a occurrence of `GetNodes not implemented` (observed inside `quay.io/cilium/cilium:v1.10.0`) a  feature or a bug?

```
hubble version # "hubble v0.8.0"
hubble list nodes --help # "List Hubble nodes ..."
hubble list nodes" # "rpc error: code = Unimplemented desc = GetNodes not implemented"
```

**Comment by rolinh** [comment]
The `GetNodes` endpoint is only implemented by Hubble Relay. Individual Hubble instances to connect to each others and thus would not be able to show all information provided by the endpoint, as seen below:
```
NAME                 STATUS      AGE      FLOWS/S   CURRENT/MAX-FLOWS       VERSION                   ADDRESS           TLS
kind-control-plane   Connected   19m41s   1.06      1549/16383 (  9.45%)    cilium v1.10.0+g952d9d3   172.18.0.5:4244   Enabled
kind-worker          Connected   19m38s   26.42     16383/16383 (100.00%)   cilium v1.10.0+g952d9d3   172.18.0.4:4244   Enabled
kind-worker2         Connected   19m40s   19.00     16383/16383 (100.00%)   cilium v1.10.0+g952d9d3   172.18.0.3:4244   Enabled
kind-worker3         Connected   19m50s   15.84     16383/16383 (100.00%)   cilium v1.10.0+g952d9d3   172.18.0.2:4244   Enabled
```
At most, name, address and TLS info could be shown for each node.

**Comment by kaworu** [comment]
When the Hubble CLI is run from a Cilium Pod, it connects to the Hubble server run by the local cilium-agent by default (i.e. unless `--server` is used or the `HUBBLE_SERVER` env variable is overridden). In that context, commands such as `observe` and `status` have a visibility limited to the Node.

The `GetNodes` endpoint is implemented by Hubble Relay, which brings multi-node visibility. There are more information and details about the Hubble architecture at https://docs.cilium.io/en/latest/internals/hubble/

**Comment by christian-2** [comment]
Yes, makes sense in light of the Hubble architecture. I'll close the issue. Thx for the clarification.
