### ISSUE TITLE
Trying to set a hubble parameter results in ENOENT.

### ISSUE THREAD

**Issue by sdake** [cilium/hubble#677]
sdake@devenv ~ [127]> ./hubble config set tls true
open /home/sdake/.config/hubble/config.yaml: no such file or directory
sdake@devenv ~ [1]> ./hubble config get tls
false

I could probably create this file, which is what I'm going to do next. The help included within the binary indicates that config.yaml is optional. The loading order also specifies this file as optional.

Cheers,
-steve

**Comment by rolinh** [comment]
Hi Steven, thanks for reporting the issue. I can reproduce and my understanding is that if the file is missing, it's not a problem but if the _directory_ is missing, then one gets the error that you report.

```
$ hubble config set tls true
open /home/robin/.config/hubble/config.yaml: no such file or directory
$ file /home/robin/.config/hubble/config.yaml 
/home/robin/.config/hubble/config.yaml  cannot open `/home/robin/.config/hubble/config.yaml ' (No such file or directory)
$ mkdir /home/robin/.config/hubble
$ hubble config set tls true
$ file /home/robin/.config/hubble/config.yaml
/home/robin/.config/hubble/config.yaml: ASCII text
```
