### ISSUE TITLE
No version numbers in Cilium Hubble container builds 

### ISSUE THREAD

**Issue by Starblade42** [cilium/hubble#71]
We're looking at integrating Cilium Hubble into our Kubernetes cluster deployments, but we're prevented from using it as a troubleshooting tool because Cilium Hubble doesn't yet have any versioned containers to pull other than the tag `latest`

As a general policy, we don't allow using the `latest` tag in our manifests to prevent unexpected issues from cropping up. For example pinning to a container version:
- Prevents running different commits of a service within the same cluster
- Prevents us from running different commits of a service across clusters (10+ and growing!)

Is Hubble near a release tag being chosen, even if it's not even close to ready to be a full release? (v0.0.0001? 🤣 )

**Comment by Starblade42** [comment]
Barring that, I can make my own mirror of `latest` on occasion and give it a versioned tag to pull from.

**Comment by glibsm** [comment]
> Prevents running different commits of a service within the same cluster

That's actually a very interesting point. Depending on the size of the rollout, you're right `:latest` can be volatile.

We of course don't foresee using `:latest` for very long, eventually using semver for releases.

I don't see much downside to arbitrary start `v0.0.1` _somewhere_ in the existing tree.

**Comment by Starblade42** [comment]
And to be clear, until things are more ready, I actually don't mind if that v0.0.1 will get updated to different commits (even tracking master!). Eventually it will be used more carefully, I'm sure. 😄

**Comment by Starblade42** [comment]
Now there's a tag for a version of some kind! Thanks. Closing.
