### ISSUE TITLE
hubble CLI help for service filtering is misleading 

### ISSUE THREAD

**Issue by lizrice** [cilium/hubble#713]
The way the service field in Hubble flows has been implemented so far is that it only works if the destination IP is the service ClusterIP. This makes the following lines from `hubble observe --help` misleading: 

```
      --from-service filter     Show all flows originating in the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
      --service filter          Show all flows related to the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
      --to-service filter       Show all flows terminating in the given service ([namespace/]<svc-name>). If namespace is not provided, 'default' is used
```

Per @gandro the ideal fix would be to extend it to do a lookup on the IP to see if the destination/source is a service backend IP and populate the fields accordingly. It likely needs some plumbing in cilium-agent first however, to have a backendIP -> service metadata index. 

In the shorter term it would be good to update the help for these items eg. 

```Shows flows where the destination IP address matches the ClusterIP address of the given service ([namespace/]<svc-name>)```

**Comment by gandro** [comment]
I think one further complication with my proposal is that we don't always know if a connection has been established via ClusterIP. Therefore, a given backend could be the endpoint for multiple services. So there would be multiple service candidates and I'm not sure what the best way would be to resolve this (the current schema only allows for one single service).

But in any case, I agree that we should update the description short term.

**Comment by ILLIDOM** [comment]
Hi all, would it be okay if I implement the short-term fix (adjusting the help messages)?

**Comment by kaworu** [comment]
@ILLIDOM absolutely, I've assigned the issue to you.

**Comment by ILLIDOM** [comment]
@kaworu Great! I have just submitted a pull request. I hope I have followed all guidelines. (This is my first contribution to the Hubble project - please inform me if you want me to change anything).
