### ISSUE TITLE
improve policy verdict event format in compact output mode

### ISSUE THREAD

**Issue by michi-covalent** [cilium/hubble#740]
right now policy verdict events look too much like flow events.

policy verdict allowed event:
```
Jun  3 17:01:09.266: default/tiefighter:53324 -> default/deathstar-6c94dcc57b-rrss6:80 L3-L4 FORWARDED (TCP Flags: SYN)
```

policy verdict denied event:
```
Jun  3 17:01:10.815: default/xwing:34218 <> default/deathstar-6c94dcc57b-rrss6:80 Policy denied DROPPED (TCP Flags: SYN)
```

we should come up with a better output format that:

- clearly indicates that it's a policy verdict event.
- shows policy verdict (https://github.com/cilium/cilium/blob/master/pkg/monitor/api/types.go#L493)
- shows traffic direction (https://github.com/cilium/cilium/blob/master/pkg/monitor/api/types.go#L487)
- indicate whether the audit mode is enabled.

**Comment by gandro** [comment]
> indicate whether the audit mode is enabled.

FWIW, I believe in audit mode the verdict is not FORWARDED but AUDIT
https://github.com/cilium/cilium/blob/246dd68057b064a2bd39bec53b061c0997bb717b/pkg/hubble/parser/threefour/parser.go#L398-L401

**Comment by michi-covalent** [comment]
yeah i think that's another confusing thing for me. i thought the audit mode is only for dropped policy verdict, like in https://docs.cilium.io/en/stable/gettingstarted/policy-creation/#enable-policy-audit-mode:

```
Policy verdict log: flow 0x63113709 local EP ID 232, remote ID 31028, proto 6, ingress, action audit, match none, 10.0.0.112 :54134 -> 10.29.50.40:80 tcp SYN
```

**Comment by pchaigno** [comment]
It is, but it's exposed as a verdict. So basically, the verdicts are:
- allowed: Packet is allowed by policies.
- denied: Packet is denied by policies.
- audit: Packet would have been denied by policies if we were not in audit mode.
