### ISSUE TITLE
Remove endpoint history from endpoint cache

### ISSUE THREAD

**Issue by gandro** [cilium/hubble#76]
The current endpoint cache in `github.com/cilium/hubble/pkg/api/v1.Endpoints` contains a few artifacts from early versions of Hubble where flows were decoded late, i.e. when a gRPC flow requested them. This meant that the endpoint cache had to keep "historic" data about endpoints around, we do this by tracking its deletion time:

https://github.com/cilium/hubble/blob/9df73911732a4d880c4fb4c7d112e45b4ed28fa0/pkg/api/v1/types.go#L29

Nowadays however, endpoint information is annotated as soon as a flow is observed, making it pointless to keep deleted endpoints around. 

We should refactor the endpoint cache and get rid of the "deleted endpoints" functionality, as it complicates the code (every getter has to check that endpoints are not deleted). This also gives us the opportunity to fix a few other issues with the current package, such as:

- Its location in `api/v1`, even though it is not really related to the gRPC interface anymore. It should probably look more similar to the fqdn/ip/service caches.
- The potential footguns it has with regards to concurrency, i.e. it returns pointers whose access is supposed to see synchronized (see https://github.com/cilium/hubble/pull/74#discussion_r374572739)

**Comment by Rolinh** [comment]
This issue is no longer relevant now that hubble server is embedded into the cilium agent.
