### ISSUE TITLE
host not found in README.md  - https://app.isovalent.com/demos/jobs.yaml

### ISSUE THREAD

**Issue by ahlfors** [cilium/hubble#764]
host not found in README.md : https://github.com/cilium/hubble/tree/v0.5/tutorials/deploy-hubble-servicemap
 - https://app.isovalent.com/demos/jobs.yaml

who knows the updated link?

**Comment by lambdanis** [comment]
@ahlfors This tutorial is for an old version of Hubble. Tutorials for newer versions are available in [Observability section of Cilium documentation](https://docs.cilium.io/en/v1.12/gettingstarted/hubble_setup/) and they're using a different demo app. Have you see those?

**Comment by ahlfors** [comment]
thanks a lot~
