### ISSUE TITLE
Observer gRPC Server: add "Latency" field to Flow(api/v1/flow), to indicate how long the flow taken

### ISSUE THREAD

**Issue by lizonglingo** [cilium/hubble#786]
Can we add a "Latency" field to the information of each flow in `api/v1/flow`, to records the time cost of each flow from the source pod to the destination pod.

In other words, Is there a way to directly obtain each flow's latency?

Recording the latency of pod communication is useful for performance tuning and cluster monitoring.

**Comment by gandro** [comment]
We do support this for HTTP flow event (thanks to Envoy): https://github.com/cilium/cilium/blob/d6483e1d26052b7f210a746ff85e919b76c9430f/api/v1/flow/flow.proto#L149

For all kind of events, this will require some additional aggregation and memory on the server. I'm not sure we would want to do this by default.

**Comment by lizonglingo** [comment]
> We do support this for HTTP flow event (thanks to Envoy): https://github.com/cilium/cilium/blob/d6483e1d26052b7f210a746ff85e919b76c9430f/api/v1/flow/flow.proto#L149
> 
> For all kind of events, this will require some additional aggregation and memory on the server. I'm not sure we would want to do this by default.

Thank you:smile:. I see this field after your reply. Some of the Pods in the cluster actually communicate using the HTTP protocol based on TCP protocol (for example the REST API). 

However, when setting the Deployment corresponding Service field like this:
```yaml
apiVersion: v1
kind: Service
...
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
...
```

But I saw that there was no L7 information in Hubbel-UI. 
![image](https://user-images.githubusercontent.com/40293922/189952903-f081fc57-40d4-4fe1-9244-64adbdaa7921.png)

It's just giving L4 (TCP) information. I also tried to output the Type of `Flow` in the debugging of the code, but the result was `L3_L4`. 
```go
fmt.Println(flow.GetType()) // L3_L4
```

HTTP is built on TCP and **how should it be configured so that Hubble can recognize that the `Flow` should be `L7` type Flow**.

**Comment by lizonglingo** [comment]
I am looking for the relevant document of configuring L7 policy in the cilium document:
https://docs.cilium.io/en/stable/policy/visibility/

I am trying to configure it.

**Comment by kaworu** [comment]
@lizonglingo you are on the right path, l7 visibility is opt-in through annotations so you need to follow the configuration guide before you can observe l7 flows.

**Comment by lizonglingo** [comment]
> @lizonglingo you are on the right path, l7 visibility is opt-in through annotations so you need to follow the configuration guide before you can observe l7 flows.

The l7 protocol information can be obtained after the configuration, thank you!
