### ISSUE TITLE
metrics udp

### ISSUE THREAD

**Issue by jcpunk** [cilium/hubble#804]
https://docs.cilium.io/en/stable/operations/metrics/#hubble-context-options lists `tcp` as a generic target.

It would be helpful if there was a similar `udp` target I could also add to my capture list.  Ideally with (basically) identical behavior.

**Comment by kaworu** [comment]
From https://docs.cilium.io/en/stable/operations/metrics/#tcp my understanding is that `tcp` enables `tcp_flags_total` for which there are no `udp` equivalent. If correct, could you please then elaborate on which `udp` metrics you are looking for?

cc @chancez

**Comment by chancez** [comment]
Also https://github.com/cilium/tetragon has some support for UDP metrics, and other network related metrics as well in case hubble does not currently offer what you need.

**Comment by jcpunk** [comment]
tetragon looks like it has what I was hunting for.  Thanks for the pointer!
