### ISSUE TITLE
Can Hubble-ui enables user certification mechanism?

### ISSUE THREAD

**Issue by younaman** [cilium/hubble#833]
I am a green hand on Hubble. When I installed the Cilium and Hubble by helm, I found that the hubble-ui seems not secured by TLS, and have no more user identification mechanism. Thus any pods/worker nodes can access the hubble-ui-service-ip:80, and access all service maps in the whole cluster. Have I missed something? Looking forward to your reply!:)

**Comment by gandro** [comment]
That's correct. If you want to expose Hubble UI outside of the cluster, it's recommended to protect it using K8s Ingress or Gateway API. 

If you expose it within the cluster, you can use Cilium Network Policies to protect access from untrusted workloads (the exact implementation will depend on your threat model).

The proprietary Cilium Enterprise distribution offers more fine-grained protections in Hubble UI for multi-tenancy use-cases, but nothing so sophisticated exists in the OSS version ofr Hubble UI: https://isovalent.com/rbac-for-multi-tenancy-requirements

**Comment by younaman** [comment]
@gandro Thanks a lot! So Hubble itself relies on the cilium to deploy more restricted access control with network policy, and Hubble itself has no more access control?

**Comment by gandro** [comment]
> @gandro Thanks a lot! So Hubble itself relies on the cilium to deploy more restricted access control with network policy, and Hubble itself has no more access control?

That's mostly correct, yes. There is mTLS authentication between Cilium Agent <-> Hubble Relay <-> Hubble UI (the latter being opt-in), but I believe Hubble UI itself does not offer mTLS towards the end-user (though this is something that could be added by e.g. running it behind a proxy).
