### ISSUE TITLE
doc: improve help message for --last option

### ISSUE THREAD

**Issue by lizrice** [cilium/hubble#861]
If you run `hubble observe ... --last 1` against a Hubble Relay you get one flow _per Hubble Server instance_.  Help text for the CLI could explain this better. Currently it says: 

```
      --last uint      Get last N flows stored in Hubble's buffer (default 20)
```

This could be changed to:  

```
      --last uint      Get last N flows stored in Hubble's buffer (default 20). When querying against Hubble Relay, this gets N flows per instance of Hubble connected to that Relay
```

**Comment by PriyaSharma9** [comment]
@lizrice I am new to Open Source, Can I pick this up?

**Comment by rolinh** [comment]
Hey @PriyaSharma9

> I am new to Open Source

Welcome to the community!

> Can I pick this up?

Sure thing! I'll assign the issue to you. Thanks!
