### ISSUE TITLE
Hubble UI shows incorrect amount of flows/s

### ISSUE THREAD

**Issue by vacan1t** [cilium/hubble#911]
Hubble GUI show vastly different flows/s than ‘hubble status’ on each cilium-agent. 

What i have found so far is that when restarting cilium daemonset, Hubble GUI shows flows/s at around 10-15k (normal), then after a day or two this climbs to hundreds of k or millions… When running `hubble status` on each cilium-agent or `hubble list nodes` and calculate them together, this is around 10-15k.

I have seen this issue in 2 out of 3 clusters. The one that does not have this issue have very little activity with around 400 flows/s.

Versions:
hubble-relay:v1.12.6
hubble-ui:v0.9.2
cilium:v1.12.6
operator-generic:v1.12.6

![hubble01](https://user-images.githubusercontent.com/101248800/220348206-06c5fdb1-936c-48e8-99f0-f49a93b51872.png)
![hubble02](https://user-images.githubusercontent.com/101248800/220348209-85c4a325-55dd-4702-a6e7-2eeb35a7154c.png)

**Comment by glibsm** [comment]
@vacan1t when you query `hubble status` against `hubble-relay` service do you see numbers that resemble the sum of all PRS on individual nodes, or one that is the same as hubble-ui?

**Comment by vacan1t** [comment]
@glibsm I would say that `hubble status` against `hubble-relay` and UI shows incorrect amount and `hubble list nodes` against `hubble-relay` show correct. Also `hubble status` against local node shows correct.

Here is output and screenshot from UI, all within a few seconds.

`hubble status --server 10.43.193.255:80
Healthcheck (via 10.43.193.255:80): Ok
Current/Max Flows: 73,710/73,710 (100.00%)
Flows/s: 1028332.01
Connected Nodes: 18/18`

`node01    Connected   42h2m49s    11.61     4095/4095 (100.00%)
node02    Connected   42h2m35s    17.42     4095/4095 (100.00%)
node03    Connected   42h4m29s    7.99      4095/4095 (100.00%)
wnode01   Connected   42h3m2s     892.23    4095/4095 (100.00%)
wnode02   Connected   42h3m32s    882.75    4095/4095 (100.00%)
wnode03   Connected   42h3m35s    953.47    4095/4095 (100.00%)
wnode04   Connected   42h4m2s     686.55    4095/4095 (100.00%)
wnode05   Connected   42h3m46s    771.71    4095/4095 (100.00%)
wnode06   Connected   42h4m28s    856.84    4095/4095 (100.00%)
wnode07   Connected   42h4m0s     1147.84   4095/4095 (100.00%)
wnode08   Connected   42h2m35s    1029.70   4095/4095 (100.00%)
wnode09   Connected   42h3m5s     1253.68   4095/4095 (100.00%)
wnode10   Connected   26h30m49s   792.36    4095/4095 (100.00%)
wnode11   Connected   24h27m41s   1012.22   4095/4095 (100.00%)
wnode12   Connected   2h33m50s    829.01    4095/4095 (100.00%)
wnode13   Connected   30m26s      451.15    4095/4095 (100.00%)
wnode14   Connected   42h3m19s    1477.04   4095/4095 (100.00%)
wnode15   Connected   42h4m15s    1252.83   4095/4095 (100.00%)`

![Screenshot 2023-02-22 at 08 35 32](https://user-images.githubusercontent.com/101248800/220554396-e434f599-6e88-42f9-919e-1818ddab7ecb.png)

**Comment by rolinh** [comment]
Thanks, this is really helpful. Would you mind giving the output of `hubble status --server 10.43.193.255:80 --output json`? Having the raw numbers for `uptime_ns` and `seen_flows` will help troubleshoot.

**Comment by vacan1t** [comment]
@rolinh Sure.
```
hubble status --server 10.43.193.255:80 --output json
{"num_flows":"73710","max_flows":"73710","seen_flows":"1856261908","uptime_ns":"9733705465380","num_connected_nodes":18,"num_unavailable_nodes":0,"version":"hubble-relay v1.12.6+g9cc8d71"}
```

**Comment by rolinh** [comment]
So the way Hubble CLI computes the average flows/s in `compact` output mode is like this (see [here](https://github.com/cilium/hubble/blob/61b09b04b208100101cf054441bd73dff8474e6b/pkg/printer/printer.go#L848-L852)):
```go
flowsPerSec := "N/A"
if uptime := time.Duration(res.UptimeNs).Seconds(); uptime > 0 {
	flowsPerSec = fmt.Sprintf("%.2f", float64(res.SeenFlows)/uptime)
}
ew.writef("Flows/s: %s\n", flowsPerSec)
```
Hubble Relay adds the `SeenFlows` number of every connected Hubble server to compute the total `SeenFlows` and uses the oldest uptime among the connected nodes to determine `uptime_ns` (see [here](https://github.com/cilium/cilium/blob/12a43872a531d3d4c755c333a785e3484c267869/pkg/hubble/relay/observer/server.go#L304-L309)).

Based on the numbers I see in the JSON output (`"seen_flows":"1856261908","uptime_ns":"9733705465380"`), the flows/s number should be `190704.55` ([Go Playground](https://go.dev/play/p/GZHCzrLaQAp)). I'm not sure how it reports a 10x larger number (`1028332.01`) in your case :thinking:. At least, both Hubble UI and the CLI seem consistent in their output.

**Comment by vacan1t** [comment]
The UI have dropped down now for some reason to 113.9K flows/s.
Here is `seen_flows` and `uptime_ns` from same time as 113.9K was show in the UI.

```
hubble status --server 10.43.193.255:80 --output json
{"num_flows":"73710","max_flows":"73710","seen_flows":"1973042999","uptime_ns":"17327182788143","num_connected_nodes":18,"num_unavailable_nodes":0,"version":"hubble-relay v1.12.6+g9cc8d71"}
```

I did a redeploy (restart) of cilium-agent daemonset now and i saw the flows/s counter i hubble ui peak at around 954M during the restart...

After a few minutes it's down to ~15K, which is about the same as `hubble list nodes --server 10.43.193.255:80` which is why i think that is the "normal" amount.

**Comment by vacan1t** [comment]
Sounds like a reasonable explanation for that part.

**Comment by vacan1t** [comment]
@rolinh Ok, a little more info about the issue.

Before my rollover/restart of cilium daemonset yesterday i saw that we hade about 4 restarts of cilium pods (because of errors or drain of nodes i guess). 

Today i checked hubble UI and it was 13.9K flows/s. I also checked CLI and it was 13852 flows/s. That's fine and sounds reasonable. 

I then deleted ONE of the cilium pods in the daemonset, and immediately saw that hubble reported something absurd like 50M flows/s. And after that it is slowly ticking down but is currently at 800K, 20 minutes after my restart of one pod. 

I guess that if we have spontaneous restarts of cilium pods the amount of flows/s in hubble UI will never be correct.

**Comment by rolinh** [comment]
Thanks @vacan1t, the information you provided was very helfpul in understanding the issue. I have a patch ready for Hubble Relay (see https://github.com/cilium/cilium/pull/23966). The TLDR is that Hubble Relay was reporting the newest uptime among the Hubble nodes instead of the oldest one on `hubble status`. Therefore, when a node was restarted, the uptime would be a very small number used as a divider for the total number of flows seen in the cluster resulting in completely wrong flows/s value.
